config/routes.rb
Rails.application.routes.draw do
  get 'tag/Taggings'
  root to: 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    has_many :taggings
    has_many :tags, through: :taggings

    def tag_list
        self.tags.collect do |tag|
            tag.name
        end.join(", ")
    end

    def tag_list=(tags_string)
        tag_names = tags_string.split(',').collect{|s| s.strip.downcase}.uniq

        new_or_found_tags = tag_names.collect { |tag_name| Tag.find_or_create_by(name: tag_name) }
        self.tags = new_or_found_tags
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :articles, through: :taggings

    def to_s
        name
    end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    include ArticlesHelper

    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
        @comment = Comment.new
        @comment.article_id = @article.id
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.save

        flash.notice = "Article '#{@article.title}' created!"

        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:id])
        Article.destroy(params[:id])

        flash.notice = "Article '#{@article.title}' deleted!"

        redirect_to articles_path
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        @article.update(article_params)
        @article.save

        flash.notice = "Article '#{@article.title}' updated!"

        redirect_to article_path(@article)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    include CommentsHelper

    def create
        @comment = Comment.new(comment_params)
        @comment.article_id = params[:article_id]
        @comment.save

        flash.notice = 'Comment submitted!'

        redirect_to article_path(@comment.article)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
        @tags = Tag.all
    end

    def show
        @tag = Tag.find(params[:id])
    end

    def destroy
        @tag = Tag.find(params[:id])
        Tag.destroy(params[:id])

        flash.notice = "Tag '#{@tag.name}' deleted!"

        redirect_to tags_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def article_params
        params.require(:article).permit(:title, :body, :tag_list)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
    def comment_params
        params.require(:comment).permit(:author_name, :body)
    end
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
    <h4>Comment by <%= comment.author_name %></h4>
    <p class="comment"><%= comment.body %></p>
    <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
    <ul>
    <% @article.errors.full_messages.each do |error| %>
        <li>
        <%= error %>
        </li>
    <% end %>
    </ul>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_field :body %>
    </p>
    <p>
        <%= f.label :tag_list %><br>
        <%= f.text_field :tag_list%>
    </p>
    <p>
        <%= f.submit %>
    </p>

    <%= link_to "<< Back to articles list", articles_path %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All articles</h1>

<ul id="articles">
    <% @articles.each do |article| %>
    <li>
        <%= link_to article.title, article_path(article), class: 'article_title', id: "article_#{article.id}" %>
    </li>
    <% end %>
</ul>


<%= link_to "Create new article", new_article_path, class: "new_article" %>

<br><br>

<%= link_to "Show all tags", tags_path, class: "all_tags" %>

app/views/articles/new.html.erb
<h1>Create new article</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p>
    Tags:
    <% @article.tags.each do |tag| %>
        <%= link_to tag.name, tag_path(tag) %>
    <% end %>
</p>

<p><%= @article.body %></p>
<br><br>
<%= link_to "<< Back to articles list", articles_path %>
<%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"} %>
<%= link_to "edit", edit_article_path(@article) %>
<br><br>
<%= render partial: 'comments/form' %>

<h2>Comments (<%= @article.comments.length %>)</h2>
<%= render partial: 'comment', collection: @article.comments %>

app/views/comments/_form.html.erb
<h3>Post a comment</h3>

<%= form_for [@article, @comment] do |f| %>
    <p>
        <%= f.label :author_name, "Your name" %><br/>
        <%= f.text_field :author_name %>
    </p>
    <p>
        <%= f.label :body %><br/>
        <%= f.text_field :body %>
    </p>
    <p>
        <%= f.submit 'Submit' %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/tags/index.html.erb
<h1>All tags</h1>

<ul id="tags">
    <% @tags.each do |tag| %>
    <li>
        <%= link_to tag.name, tag_path(tag), class: 'tag_name', id: "tag_#{tag.id}" %>
    </li>
    <% end %>
</ul>

<br><br>

<%= link_to "<< Back to all articles list", articles_path %>

app/views/tags/show.html.erb
<h1>Articles tagged with <%= @tag.name %></h1>

<ul>
    <% @tag.articles.each do |article| %>

    <li><%= link_to article.title, article_path(article) %></li>

    <% end %>
</ul>

<br><br>

<%= link_to "<< Back to all tags list", tags_path %>

<%= link_to "delete", tag_path(@tag), method: :delete, data: {confirm: "Really delete the tag?"} %>